spring:
  application:
    name: notification-service
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 854621001@smtp-brevo.com
    sender: socialmediaemail1711@gmail.com
    password: mVjMJc4NLDPHwxAh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    addresses: amqps://ehzzfrui:666BNJl25PqRl0gFsZJMBa-8x6Y_zSbH@kebnekaise.lmq.cloudamqp.com/ehzzfrui


  messaging:
    exchange: social-events-exchange
    queue: queue
    routing-key: event.binding

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

