spring:
  application:
    name: notification-service
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    sender: ${SPRING_MAIL_SENDER}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES}


  messaging:
    exchange: ${SPRING_MESSAGING_EXCHANGE}
    queue: ${SPRING_MESSAGING_QUEUE}
    routing-key: ${SPRING_MESSAGING_ROUTING_KEY}

